steps:
- name: 'spinnakerrelease/gradle_cache'
  env: ["GRADLE_USER_HOME=/gradle_cache/.gradle"]
  entrypoint: "bash"
  args: [ "-c", "./gradlew halyard-web:installDist -x test"]
- name: 'gcr.io/cloud-builders/docker'
  args: ["build", "-t", "gcr.io/$PROJECT_ID/halyard:$COMMIT_SHA", "-t", "gcr.io/$PROJECT_ID/halyard:latest", "-f", "Dockerfile.slim", "."]
images:
- 'gcr.io/$PROJECT_ID/halyard:$COMMIT_SHA'
- 'gcr.io/$PROJECT_ID/halyard:latest'
timeout: 25m
