apiVersion: v1
kind: Service
metadata:
  name: {%service-name%}
  namespace: {%namespace%}
  labels:
    app: hal
    stack: clouddriver
spec:
  ports:
    - port: {%port%}
  selector:
    load-balancer-{%service-name%}: "true"

---

apiVersion: extensions/v1beta1
kind: ReplicaSet
metadata:
  name: {%component-name%}
  namespace: {%namespace%}
  labels:
    app: spin
    stack: {%component-type%}
    detail: bootstrap
spec:
  replicas: 1
  selector:
    matchLabels:
      server-group: {%component-name%}
  template:
    metadata:
      labels:
        server-group: {%component-name%}
        load-balancer-{%service-name%}: "true"
    spec:
      containers:
          #TODO(lwander) pick a 'stable' image
        - image: quay.io/spinnaker/clouddriver:v1.498.0
          name: clouddriver
          ports:
            - containerPort: {%port%}
              name: clouddriver
          volumeMounts:
            - mountPath: /opt/spinnaker/config
              name: hal-clouddriver-config
            - mountPath: /root/.kube
              name: hal-kube-config
          readinessProbe:
            httpGet:
              path: /credentials
              port: {%port%}
            initialDelaySeconds: 20
            timeoutSeconds: 1
      volumes:
        - name: hal-clouddriver-config
          secret:
            secretName: {%clouddriver-config%}
        - name: hal-kube-config
          secret:
            secretName: {%creds-config%}

