server:
  port: 8064

halconfig:
  filesystem:
    path: ~/.hal/config

spinnaker:
  artifacts:
    debian: https://dl.bintray.com/spinnaker-releases/debians
    docker: gcr.io/spinnaker-marketplace
  config:
    input:
      writerEnabled: true
      gcs:
        jsonPath: /usr/local/google/home/lwander/.gcp/spinnaker-marketplace-account.json
      bucket: halconfig

endpoints:
  shutdown:
    enabled: true

retrofit:
  logLevel: BASIC
