server:
  port: 8064

halconfig:
  filesystem:
    path: ~/.hal/config

spinnaker:
  artifacts:
    debian: https://dl.bintray.com/spinnaker-team/spinnakerbuild
    docker: gcr.io/spinnaker-marketplace
  config:
    input:
      writerEnabled: false
      bucket: halconfig

endpoints:
  shutdown:
    enabled: true

retrofit:
  logLevel: BASIC
