apiVersion: apps/v1beta2 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: spin-{{ name }}
  namespace: {{ namespace }}
  annotations:
    moniker.spinnaker.io/application: '"spin"'
    moniker.spinnaker.io/cluster: '"{{ name }}"'
  labels:
    app: spin
    cluster: spin-{{ name }}
    app.kubernetes.io/name: {{ name }}
    app.kubernetes.io/managed-by: halyard
    app.kubernetes.io/part-of: spinnaker
    app.kubernetes.io/version: {{ version }}
spec:
  replicas: {{ replicas }}
  selector:
    matchLabels:
      app: spin
      cluster: spin-{{ name }}
  template:
    metadata:
      annotations: {
      {% for key, value in podAnnotations.items() %}
              "{{ key }}" : "{{ value }}"{% if not loop.last %}, {% endif %}
      {% endfor %}}
      labels:
        app: spin
        cluster: spin-{{ name }}
        app.kubernetes.io/name: {{ name }}
        app.kubernetes.io/managed-by: halyard
        app.kubernetes.io/part-of: spinnaker
        app.kubernetes.io/version: {{ version }}
        {% for key, value in podLabels.items() %}
        "{{ key }}" : "{{ value }}"{% if not loop.last %}, {% endif %}
        {% endfor %}
    spec: {{ podSpec }}
