{
  "containers": [
    {% for container in containers %}
    {{ container }} {% if not loop.last %} , {% endif %}
    {% endfor %}
  ],

  {% if initContainers != null %}
  "initContainers": [
    {% for c in initContainers %}
    {{ c }} {% if not loop.last %} , {% endif %}
    {% endfor %}
  ],
  {% endif %}

  "terminationGracePeriodSeconds": {{ terminationGracePeriodSeconds }},

  "volumes": [
    {% for volume in volumes %}
    {{ volume }} {% if not loop.last %} , {% endif %}
    {% endfor %}
  ]
}