{
  "apiVersion": "v1",
  "kind": "Secret",
  "metadata": {
    "name": "{{ name }}",
    "namespace": "{{ namespace }}"
  },
  "type": "Opaque",
  "data": {
    {% for file, contents in files.items() %}
    "{{ file }}": "{{ contents }}" {% if not loop.last %} , {% endif %}
    {% endfor %}
  }
}
