kind: Service
apiVersion: v1
metadata:
  name: spin-{{ name }}
  namespace: {{ namespace }}
  labels:
    app: spin
    cluster: spin-{{ name }}
spec:
  selector:
    app: spin
    cluster: spin-{{ name }}
  type: {{ type }}
  ports:
  - protocol: TCP
    port: {{ port }}
    targetPort: {{ port }}
  {% if nodePort and type == "NodePort" %}
    nodePort: {{ nodePort }}
  {% endif %}