apiVersion: v1
kind: ServiceAccount
metadata:
  name: spin-{{ name }}
  namespace: {{ namespace }}
  labels:
    app: spin
    cluster: spin-{{ name }}
  annotations: {
  {% for key, value in serviceAccountAnnotations.items() %}
    "{{ key }}": "{{ value }}"{% if not loop.last %}, {% endif %}
  {% endfor %}}
