kind: Service
apiVersion: v1
metadata:
  name: spin-{{ name }}
  namespace: {{ namespace }}
  labels:
    app: spin
    cluster: spin-{{ name }}
spec:
  selector:
    app: spin
    cluster: spin-{{ name }}
  ports:
  - protocol: TCP
    port: {{ port }}
    targetPort: {{ port }}
